// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm0oqm0t3xyinFHL3Q5oCMIgU76HuEx68',
    appId: '1:849290243646:web:baf46e0d6e8108c7742b6f',
    messagingSenderId: '849290243646',
    projectId: 'deeplinking-53cf9',
    authDomain: 'deeplinking-53cf9.firebaseapp.com',
    storageBucket: 'deeplinking-53cf9.appspot.com',
    measurementId: 'G-LW34BL7D4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXCxffHFc1cmDadI4T0vwkPKwZu1r95kw',
    appId: '1:849290243646:android:d826df5f85e44b8a742b6f',
    messagingSenderId: '849290243646',
    projectId: 'deeplinking-53cf9',
    storageBucket: 'deeplinking-53cf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxXq80_1z0vHTU1KgN61zEPrVt0tJtUOo',
    appId: '1:849290243646:ios:701a7a3d670584c2742b6f',
    messagingSenderId: '849290243646',
    projectId: 'deeplinking-53cf9',
    storageBucket: 'deeplinking-53cf9.appspot.com',
    iosBundleId: 'com.example.deeplinking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxXq80_1z0vHTU1KgN61zEPrVt0tJtUOo',
    appId: '1:849290243646:ios:701a7a3d670584c2742b6f',
    messagingSenderId: '849290243646',
    projectId: 'deeplinking-53cf9',
    storageBucket: 'deeplinking-53cf9.appspot.com',
    iosBundleId: 'com.example.deeplinking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm0oqm0t3xyinFHL3Q5oCMIgU76HuEx68',
    appId: '1:849290243646:web:e039546e75000b3a742b6f',
    messagingSenderId: '849290243646',
    projectId: 'deeplinking-53cf9',
    authDomain: 'deeplinking-53cf9.firebaseapp.com',
    storageBucket: 'deeplinking-53cf9.appspot.com',
    measurementId: 'G-K39RX23CRJ',
  );
}
